server:
  port: 10050
spring:
  application:
    name: gulimall-product
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.236.128:3307/gulimall_pms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.236.128:8848
    #阿里云oss对象存储
    alicloud:
      access-key: LTAI5t9DJuV6q8CqztEXdJ3b
      secret-key: RzVNAZASOr8MgOMHe33n8LoG7RX8ZH
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        #mybatis
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.atguigu.gulimall: debug
