server:
  port: 12000
spring:
  application:
    name: gulimall-search
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.236.128:3307/gulimall_pms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.236.128:8848

logging:
  level:
    com.atguigu.gulimall: debug
